#!/usr/bin/with-contenv bash
# shellcheck shell=bash

# permissions function
chownfiles () {
    lsiown -R abc:abc \
        /app/quassel-web/public \
        /config
}

# env variable validation
VARS=( \
QUASSEL_CORE \
QUASSEL_PORT \
)
for i in "${VARS[@]}"; do
    if [[ -z ${!i+x} ]]; then
        echo "${i} is required to setup container with env variables falling back to config file"
        echo "You will need to manually modify /config/settings-user.js"
        if [[ ! -f /config/settings-user.js ]]; then
            cp -pr /app/quassel-web/settings.cjs /config/settings-user.js
        fi
        chownfiles
        exit 0
    fi
done

echo "QUASSEL_CORE set, injecting env variables into settings.js"
cp -pr /app/quassel-web/settings.cjs /app/quassel-web/settings-env.js
# Env variable injection
    sed -i \
        -e "s#host:.*//#host: '${QUASSEL_CORE}', //#g" \
        -e "s#port:.*,// quasselcore#port: ${QUASSEL_PORT}, // quasselcore#g" \
        -e "s#forcedefault:.*//#forcedefault: true, //#g" \
        -e "s#mode:.*// can be 'http'#mode: 'http', // can be 'http'#g" \
        -e "s#port:.*// Port on which to listen#port: 64080, // Port on which to listen#g" \
        /app/quassel-web/settings-env.js && \
if [[ "${URL_BASE+x}" ]]; then
    sed -i "s#prefixpath:.*//#prefixpath: \'${URL_BASE}\', //#g"
    /app/quassel-web/settings-env.js
fi

# file permissions
chownfiles
