#!/usr/bin/with-contenv bash

cd /app/quassel-web || true
# determine config file to use
if [ -f "/app/quassel-web/settings-env.js" ] && \
    [ "${QUASSEL_CORE+x}" ]; then
    CONFIG="/app/quassel-web/settings-env.js"
else
    CONFIG="/config/settings-user.js"
fi

NODE_ENV=production exec \
    s6-setuidgid abc node app.js -c "${CONFIG}"
