#!/usr/bin/with-contenv bash
# shellcheck shell=bash

if [[ -f "/app/quassel-web/settings-env.cjs" ]] && [[ "${QUASSEL_CORE+x}" ]]; then
    CONFIG="/app/quassel-web/settings-env.cjs"
else
    CONFIG="/config/settings-user.cjs"
fi

export NODE_ENV=production

exec \
    s6-notifyoncheck -d -n 300 -w 1000 -c "nc -z localhost 64443" \
        cd /app/quassel-web s6-setuidgid abc node app.js --config "${CONFIG}"
