#!/usr/bin/with-contenv bash
# shellcheck shell=bash

if [[ -f "/app/quassel-web/settings-env.cjs" ]] && [[ "${QUASSEL_CORE+x}" ]]; then
    CONFIG="/app/quassel-web/settings-env.cjs"
else
    CONFIG="/config/settings-user.cjs"
fi

export NODE_ENV=production

PORT=$(sed -n '/webserver: {/,/},/p' "${CONFIG}" | grep 'port:' | awk -F ':' '{print $2}' | cut -f1 -d ',' | tr -d '[:space:]')

if [[ "${PORT}" != "null" ]]; then
    exec \
        s6-notifyoncheck -d -n 300 -w 1000 -c "nc -z localhost ${PORT}" \
            cd /app/quassel-web s6-setuidgid abc node app.js --config "${CONFIG}"
else
    cd /app/quassel-web || exit 1
    exec \
        s6-setuidgid abc node app.js --config "${CONFIG}"
fi
